### ISSUE TITLE
Sugerencias

### ISSUE THREAD

**Issue by Escorbutopia** [D3uxx/vrp_business#1]
Hola, te felicito por tu empeño en hacer un script para comprar empresas, es un buen comienzo, y te voy a dar unos pequeños consejos para que funcione mejor.

Primero los inconvenientes que veo en el script:
1-Estas creando triggers para enviar notificaciones desde el servidor, cuando el vrp te permite hacerlo directamente con vRPclient(player,{"mensaje"}))
2- cualquiera puede comprar la empresa, aunque ya la hayan comprado otro, eso puedes limitarlo haciendo una variable donde guardes los usuarios del grupo, local empresarios = vrp.getusersbygroup({"HBO}) (no está bien escrito pero lo pongo de memoria), y luego hacer un if not #empresarios > 0 then y dentro lo de dar grupo, así solo habrá uno con esa empresa.
3- solo tienes una empresa aunque tienes un array creado para tener varias, simplemente donde compruebas la distancia tiene que estar en un for k,v in pair(array de empresas), y que vaya comprobando las coordenadas de cada empresa, también añadiria a cada empresa el grupo y se lo añadiría al trigger, así te es más fácil comprobar si hay alguien en ese grupo.

Eso son solo algunos consejos, si necesitas ayuda sabes donde encontrarme creo.

Un saludo

**Comment by c0deina** [comment]
Gracias por comentar y los consejos, es el primer script que escribo desde 0 por lo cual esta muy verde pero espero mejorarlo poco a poco, 

Lo de limitar las empresas es una gran idea, esta noche intentaré implementarla, lo de tener un array con empresas es porque en un principio tenía pensado crear varias para probar, pero me estaba dando problemas así que lo limité a uno y lo subi para ver si alguien querría ayudar o intentar utilizarlo al menos como base para algún proyecto próximo.

Difícil encontrarte en estos momentos estando fuera del discord, ya intentaré volver a entrar 👍 

Saludos,
aNdrew.
